### PR TITLE
Fixup storage drivers

### LINKED ISSUE #121: if volcli volume remove fails, use lock is still held
probably just needs a defer in the right spot.

### LINKED ISSUE #122: if volplugin map/mount fails, rbd lock is not freed in some situations

### PR DESCRIPTION
**Pull request by erikh**
This incorporates many changes that improve the stability of volmaster create operations, which was failing in a lot of scenarios on slower machines.

PTAL @mapuri @unclejack, this is a big change so please review carefully.

closes #121 
closes #122

### CODE REVIEW

**Comment by unclejack** [comment]
LGTM

File: volmaster/daemon.go [hunk 1]
```diff
@@ -96,11 +97,13 @@ func (d daemonConfig) handleRemove(w http.ResponseWriter, r *http.Request) {
 	}
 
 	if err := removeVolume(vc); err != nil {
+		d.config.RemoveUse(uc, false)
```
Comment (mapuri) [inline volmaster/daemon.go]: may be we should just defer call to `d.config.RemoveUse` from this point on?

**Comment by mapuri** [comment]
a lot of cleanup!! LGTM, other than one minor comment.
