### PR TITLE
Several issues with copying snapshots

### LINKED ISSUE #294: Error while copying snapshot to a volume
I see below error while calling this rest endpoint
POST /volumes/copy

Supplied json
{
  "volume": "postgres-vol",
  "policy": "db-storage-policy",
  "Options": {
       "target": "volumefromSnapshot",
	   "snapshot": "2016-06-03-15:00:00.573457352-+0000-UTC"
	}
}
Publishing Volume: Creating new volume "volumefromSnapshot" from volume "db-storage-policy/postgres-vol", snapshot "2016-06-03-15:00:00.573457352-+0000-UTC": Locking Operation Failed
	github.com/contiv/volplugin/errors.init [errors.go 49]
	github.com/contiv/volplugin/config.init [volume.go 467]
	main.init [cli.go 61]
	runtime.main [proc.go 177]
	runtime.goexit [asm_amd64.s 1998]
	github.com/contiv/volplugin/volmaster.(*DaemonConfig).handleCopy [daemon.go 484]
	github.com/contiv/volplugin/volmaster.(*DaemonConfig).(github.com/contiv/volplugin/volmaster.handleCopy)-fm [daemon.go 79]
	github.com/contiv/volplugin/volmaster.logHandler.func1 [daemon.go 154]
	net/http.HandlerFunc.ServeHTTP [server.go 1618]
	github.com/contiv/volplugin/vendor/github.com/gorilla/mux.(*Router).ServeHTTP [mux.go 98]
	net/http.serverHandler.ServeHTTP [server.go 2081]
	net/http.(*conn).serve [server.go 1472]
	runtime.goexit [asm_amd64.s 1998]
	github.com/contiv/volplugin/errors.init [errors.go 12]
	github.com/contiv/volplugin/config.init [volume.go 467]
	main.init [cli.go 61]
	runtime.main [proc.go 177]
	runtime.goexit [asm_amd64.s 1998]

This is what my policy looks like:
{"name":"db-storage-policy","create":{"size":"30MB","filesystem":"ext4"},"runtime":{"snapshots":true,"snapshot":{"frequency":"90m","keep":30},"rate-limit":{"write-iops":1000,"read-iops":1000,"write-bps":100000000,"read-bps":100000000}},"driver":{"pool":"rbd"},"filesystems":{"btrfs":"mkfs.btrfs %","ext4":"mkfs.ext4 -m0 %","falsefs":"/bin/false"},"backends":{"crud":"ceph","mount":"ceph","snapshot":"ceph"}}

### PR DESCRIPTION
**Pull request by erikh**
* We failed to acquire a lock when the volume was mounted, which timed out preventing the copy and a lengthy round trip on the error. The code was adjusted to remove the requirement that the volume would not be mounted.
* Several bugs in the ceph storage driver around copying were fixed:
  * when EBUSY is returned during a snapshot volume protect, *do not* fail. It is simply because the snapshot  is already protected.
  * when EEXIST is returned during any copy operation, the volume named would be cleaned up as a part of the healing process, which would in turn remove the volume if it exists. Previously, this would clean up any named volume.

Fixes #294 /cc @vishal-j

### CODE REVIEW

**Comment by erikh** [comment]
ready for review.

File: storage/backend/ceph/ceph.go [hunk 1]
```diff
@@ -397,35 +398,35 @@ func (c *Driver) CopySnapshot(do storage.DriverOptions, snapName, newName string
...
-			cmd := exec.Command("rbd", "snap", "unprotect", intOrigName, "--snap", snapName, "--pool", do.Volume.Params["pool"])
-			if er, err := runWithTimeout(cmd, do.Timeout); err != nil || er.ExitStatus != 0 {
-				log.Errorf("Error encountered unprotecting new volume %q for volume %q, snapshot %q: %v, %v", newName, intOrigName, snapName, err, er.Stderr)
-				return
+			if newerr, ok := err.(*errored.Error); ok && !newerr.Contains(errors.Exists) {
+				log.Warnf("Error received while copying snapshot: %v. Attempting to cleanup.", err)
+				cmd = exec.Command("rbd", "rm", intNewName, "--pool", do.Volume.Params["pool"])
+				if er, err := runWithTimeout(cmd, do.Timeout); err != nil || er.ExitStatus != 0 {
+					log.Errorf("Error encountered removing new volume %q for volume %q, snapshot %q: %v, %v", intNewName, intOrigName, snapName, err, er.Stderr)
+					return
```
Comment (mapuri) [inline storage/backend/ceph/ceph.go]: Just wondering, if the rbd clone command (below) were to fail without creating a new volume, then returning here will skip the unprotect part that follows. Is that desired?

**Comment by mapuri** [comment]
LGTM other than one minor clarification

File: storage/backend/ceph/ceph.go (hunk 1 above)
Comment (erikh) [inline storage/backend/ceph/ceph.go]: Yeha; I think you're right. Let's walk through that error, I will fix it.

**Comment by dseevr** [comment]
LGTM aside from the thing @mapuri flagged

**Comment by erikh** [comment]
@mapuri please revisit and tell me if you're comfortable with the new refactor of this to fit your requirement. Thanks!

**Comment by mapuri** [comment]
thanks for addressing this @erikh 

LGTM
