### PR TITLE
Fix multi pool snapshots

### LINKED ISSUE #362: [volsupervisor] rbd clone invocation incorrect for non-default pools
ceph version: 0.94.6
volplugin version: 0.20.0

with a pool named "example", the following invocation of volcli:

```
$ volcli  volume snapshot copy policy1/volume1 2016-07-22-22:30:00.76904695-+0000-UTC  volume1-clone1
```

invokes:

```
$ rbd clone policy1.volume1 policy1.volume1-clone1 --snap 2016-07-22-22:30:00.76904695-+0000-UTC --pool example
rbd: error opening pool rbd: (2) No such file or directory
```

this results in a  500 error from the API server and the clone isn't created.  the correct rbd invocation is:

```
rbd clone example/policy1.volume1 example/policy1.volume1-clone1 --snap 2016-07-22-22:30:00.76904695-+0000-UTC
```

the first `example/` is the source pool and the second is the destination pool. the `--pool` flag isn't necessary.

### PR DESCRIPTION
**Pull request by erikh**
Ceph's pool/image syntax is now used. This corrects many errors taking snapshots from alternative pools, which previously attempt to use `--pool` which unfortunately is not supported for some snapshot operations. The pool syntax has been unified in the call to mkpool().

Fixes #362

### CODE REVIEW

**Comment by erikh** [comment]
@yuva29 @dseevr PTAL

File: storage/backend/ceph/ceph.go [hunk 1]
```diff
@@ -41,6 +42,21 @@ type Driver struct {
 	mountpath string
 }
 
+func (c *Driver) mkMountPath(poolName, intName string) (string, error) {
+	// Directory to mount the volume
+	volumePath := filepath.Join(c.mountpath, mkpool(poolName, intName))
+	rel, err := filepath.Rel(c.mountpath, volumePath)
+	if err != nil || strings.Contains(rel, "..") {
+		return "", errors.MountFailed.Combine(errored.Errorf("Calculated volume path would escape subdir jail: %v", volumePath))
```
Comment (dseevr) [inline storage/backend/ceph/ceph.go]: Security-wise, will we ever have to worry about symlink resolution in mount targets?

**Comment by dseevr** [comment]
LGTM

File: storage/backend/ceph/ceph.go (hunk 1 above)
Comment (erikh) [inline storage/backend/ceph/ceph.go]: I'll have to test but mounting through a symlink probably causes EINVAL

Comment (erikh) [inline storage/backend/ceph/ceph.go]: I'll get back to you on this.

Comment (dseevr) [inline storage/backend/ceph/ceph.go]: At least for bind mounts, symlinks are resolved during mounts:

```sh
root:/tmp$ mkdir realdir
root:/tmp$ touch realdir/data.txt
root:/tmp$ ln -s realdir symlink
root:/tmp$ mkdir mountpoint
root:/tmp$ mount --bind /tmp/symlink /tmp/mountpoint/
root:/tmp$ ls -l /tmp/mountpoint/
data.txt
```

I have no idea if it applies at all to what we're doing, but I was curious.

Comment (erikh) [inline storage/backend/ceph/ceph.go]: I'll look into this, we need the ceph device to exhibit this behavior.

I'm also not 100% certain it matters because we'll be overwriting the dir with the mounted content anyway.

Comment (dseevr) [inline storage/backend/ceph/ceph.go]: Cool, thanks.

File: storage/backend/ceph/ceph_test.go [hunk 2]
```diff
@@ -109,6 +128,20 @@ func (s *cephSuite) TestMountUnmountVolume(c *C) {
...
+		Timeout:   5 * time.Second,
+	}
+
+	if done {
+		return
+	}
+
+	done = true
+
+	goto again
```
Comment (yuva29) [inline storage/backend/ceph/ceph_test.go]: In case of successful completion during the first run, why are we preforming another loop of execution rather returning? 

What is the actual intention of using goto here?

Comment (yuva29) [inline storage/backend/ceph/ceph_test.go]: Does it actually perform 2 rounds of execution with different volume specification(volumeSpec, volumeSpecTestPool ? And is it why the function doesn't return on first successful completion?

Comment (erikh) [inline storage/backend/ceph/ceph_test.go]: yes, it performs 2 rounds. there is no need for return in the test functions -- that doesn't accomplish anything. `c.Assert` will stop the routine if anything fails.

**Comment by yuva29** [comment]
LGTM

**Comment by erikh** [comment]
Leaving this open until I get the opportunity  to test the mount/symlink semantics.

**Comment by erikh** [comment]
Ok I looked into this. I found an exploit but it's hard to trigger. I'll be putting in an issue for it anyways.

In summary: 

Since the data will always originate from the RBD or NFS mount or etc, this will ensure that no data from the host can leak into the container. That's good.

The bad: if I were to manage this:

`ln -s / /path/to/mountpoint`

I could effectively mount over the whole root filesystem.

NOW

both of these strategies rely on being able to put a symlink on the host. I'm not very worried about this as if the host is compromised, well...

So I'm not going to make this very high priority for now. If there is an easier to exploit or pure remote exploit we can offer here, I would definitely raise the priority.
