### PR TITLE
volmaster: correct an issue where a 500 would be sent in the event a 404 should be sent.

### LINKED ISSUE #263: volcli volume remove fails to remove rbd volume (500 error) but removes volume in etcd
This should not happen, perhaps the order should be reversed. `force-remove` solves the orphaned volplugin volume problem.

### PR DESCRIPTION
**Pull request by erikh**
Signed-off-by: Erik Hollensbe <erik+github@hollensbe.org>

fixes #263

### CODE REVIEW

File: volmaster/daemon.go [hunk 1]
```diff
@@ -423,30 +423,38 @@ func (d *DaemonConfig) handleRemove(w http.ResponseWriter, r *http.Request) {
...
 			return err
 		}
 
 		if err == errNoActionTaken {
-			goto publish
+			return complete()
 		}
 
 		if !exists {
+			etcdRemove()
```
Comment (mapuri) [inline volmaster/daemon.go]: I might be reading this wrong, but may be this should be `return etcdRemove()` ? Otherwise I think we will fall through and call `complete()` below which will call `etcdRemove()` again and fail.

Comment (erikh) [inline volmaster/daemon.go]: no, it returns `config.ErrNotExist` which is the desired behavior, and ensures the record was removed from etcd. This is the actual problem here that is being fixed.

I should perhaps comment this logic. I don't like it, but it seems to want to fit in this way.

Comment (mapuri) [inline volmaster/daemon.go]: ah, yes you are right ! my bad I missed the return on the next line.

**Comment by mapuri** [comment]
LGTM

**Comment by unclejack** [comment]
LGTM
